module Userplex
  module Models
    module Store
      type order_create_params =
        {  } & Userplex::Internal::Type::request_parameters

      class OrderCreateParams < Userplex::Models::Order
        extend Userplex::Internal::Type::RequestParameters::Converter
        include Userplex::Internal::Type::RequestParameters

        def initialize: (?request_options: Userplex::request_opts) -> void

        def to_hash: -> { request_options: Userplex::RequestOptions }
      end
    end
  end
end
