module Userplex
  module Models
    type event_track_response = { success: bool }

    class EventTrackResponse < Userplex::Internal::Type::BaseModel
      attr_accessor success: bool

      def initialize: (success: bool) -> void

      def to_hash: -> { success: bool }
    end
  end
end
