module Userplex
  module Models
    type event_new_response = { success: bool }

    class EventNewResponse < Userplex::Internal::Type::BaseModel
      attr_accessor success: bool

      def initialize: (success: bool) -> void

      def to_hash: -> { success: bool }
    end
  end
end
