module Userplex
  module Models
    type event_track_params =
      { name: String, user_id: String, timestamp: Time }
      & Userplex::Internal::Type::request_parameters

    class EventTrackParams < Userplex::Internal::Type::BaseModel
      extend Userplex::Internal::Type::RequestParameters::Converter
      include Userplex::Internal::Type::RequestParameters

      attr_accessor name: String

      attr_accessor user_id: String

      attr_reader timestamp: Time?

      def timestamp=: (Time) -> Time

      def initialize: (
        name: String,
        user_id: String,
        ?timestamp: Time,
        ?request_options: Userplex::request_opts
      ) -> void

      def to_hash: -> {
        name: String,
        user_id: String,
        timestamp: Time,
        request_options: Userplex::RequestOptions
      }
    end
  end
end
