module Userplex
  module Models
    type pet_upload_image_params =
      { image: Userplex::Internal::file_input, additional_metadata: String }
      & Userplex::Internal::Type::request_parameters

    class PetUploadImageParams < Userplex::Internal::Type::BaseModel
      extend Userplex::Internal::Type::RequestParameters::Converter
      include Userplex::Internal::Type::RequestParameters

      attr_accessor image: Userplex::Internal::file_input

      attr_reader additional_metadata: String?

      def additional_metadata=: (String) -> String

      def initialize: (
        image: Userplex::Internal::file_input,
        ?additional_metadata: String,
        ?request_options: Userplex::request_opts
      ) -> void

      def to_hash: -> {
        image: Userplex::Internal::file_input,
        additional_metadata: String,
        request_options: Userplex::RequestOptions
      }
    end
  end
end
