module Userplex
  module Models
    type user_update_params =
      {  } & Userplex::Internal::Type::request_parameters

    class UserUpdateParams < Userplex::Models::User
      extend Userplex::Internal::Type::RequestParameters::Converter
      include Userplex::Internal::Type::RequestParameters

      def initialize: (?request_options: Userplex::request_opts) -> void

      def to_hash: -> { request_options: Userplex::RequestOptions }
    end
  end
end
