module Userplex
  module Models
    type user_create_with_list_params =
      { items: ::Array[Userplex::User] }
      & Userplex::Internal::Type::request_parameters

    class UserCreateWithListParams < Userplex::Internal::Type::BaseModel
      extend Userplex::Internal::Type::RequestParameters::Converter
      include Userplex::Internal::Type::RequestParameters

      attr_reader items: ::Array[Userplex::User]?

      def items=: (::Array[Userplex::User]) -> ::Array[Userplex::User]

      def initialize: (
        ?items: ::Array[Userplex::User],
        ?request_options: Userplex::request_opts
      ) -> void

      def to_hash: -> {
        items: ::Array[Userplex::User],
        request_options: Userplex::RequestOptions
      }
    end
  end
end
