module Userplex
  module Resources
    class Events
      def track: (
        name: String,
        user_id: String,
        ?timestamp: Time,
        ?request_options: Userplex::request_opts
      ) -> Userplex::Models::EventTrackResponse

      def initialize: (client: Userplex::Client) -> void
    end
  end
end
