module Userplex
  module Resources
    class Store
      attr_reader orders: Userplex::Resources::Store::Orders

      def list_inventory: (
        ?request_options: Userplex::request_opts
      ) -> Userplex::Models::store_list_inventory_response

      def initialize: (client: Userplex::Client) -> void
    end
  end
end
