module Userplex
  module Resources
    class Users
      def identify: (
        user_id: String,
        ?email: String,
        ?name: String,
        ?properties: ::Hash[Symbol, top?],
        ?request_options: Userplex::request_opts
      ) -> Userplex::Models::UserIdentifyResponse

      def initialize: (client: Userplex::Client) -> void
    end
  end
end
